baseURL: "https://61008382dc94cf4a0aefd39f--sanjan-vijayakumar.netlify.app/"
languageCode: "en-us"
title: "Hugo-profile"

googleanalytics: UA-167646412-8
disqusShortname: 
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"
    - name: "Version2"
      Url: "https://v2.profile.gurusabarish.tech"
    - name: "Version1"
      Url: "https://v1.profile.gurusabarish.tech"
  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Sanjan Vijayakumar"
  profession: "Data Scientist"
  github: "https://github.com/sanjsvk"
  linkedin: "https://www.linkedin.com/in/sanjanvijayakumar/"
  twitter: "https://twitter.com/sanjansvk"
  instagram: "https://www.instagram.com/sanj.an/"
  facebook: "https://www.facebook.com/sanjan.vijayakumar/"

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Sanjan Vijayakumar, a passionate Data Scientist. <br> I like to leverage the power of data to build insights that help make valuable business decisions"
  skills:
    - name: Python
      percentage: 90
    - name: SQL
      percentage: 85
    - name: Machine Learning/Deep Learning
      percentage: 80
    - name: AWS
      percentage: 75
    - name: Google Cloud Platform
      percentage: 70

  # Experience
  disable_experience: false
  experience:
    - company: "LabCorp"
      role: "Data Science Intern"
      startdate: May 2021
      enddate: present
      featuredpoints:
        - point: Created an installable data-platform package reducing data pre-processing time by 40%.
        - point: Built and deployed a recommendation system to recommend tests to users.
        - point: Devised a framework for storage and retrieval of test reference ranges in AWS.
    - company: "eMotionRx, Inc"
      role: "Data Science co-op"
      startdate: May 2020
      enddate: Dec 2020
      featuredpoints:
        - point: Orchestrated the migration of on-prem sensor data onto Google Cloud Platform.
        - point: Streamlined ETL jobs using Cloud Dataproc reducing pre-processing runtime by 30%.
        - point: Designed a random forest model with 94% accuracy for pressure distribution on a sole.

  # Education
  disable_education: false
  education:
    - degree: "Master of Science"
      branch: "Data Science"
      university: "Northeastern University"
      startedyear: "2019"
      graduation: "2021"
    - degree: "Bachelor of Engineering"
      branch: "Electronics and Communication"
      university: "Visvesvaraya Technological University"
      startedyear: "2015"
      graduation: "2019"

  # Projects
  disable_projects: false
  projects:
    - name: "Attention Based Image Captioning System"
      img: /images/project.jpg
      githublink: "https://github.com/sanjsvk/Attention-based-image-captioning"
      description: "An image caption generator that uses a local attention model on top of a VGG-16 model as an application of NLP and deep learning"
    - name: "Restaurant Business Analysis and Optimization Using Yelp Review Data"
      img: /images/project.jpg
      githublink: "https://github.com/sanjsvk/Yelp-Restaurant-Business-Analysis"
      description: "A project which aims at gaining insights and helping restaurants objectively interpret their reviews."
    - name: "Time Series Forecasting for energy consumption prediction"
      img: /images/project.jpg
      githublink: "https://github.com/sanjsvk/Time-Series-Forecasting"
      description: "A project to predict energy consumption in buildings with time-series hourly meter readings for one year."
    - name: "CycleGANs"
      img: /images/project.jpg
      githublink: "https://github.com/sanjsvk/CycleGANs"
      description: "A project to understand the operation of CycleGANs with a few examples."


  # Achievements
  disable_achievements: false
  achievements:
    - title: Semi-finalist - EY Data Science challenge 2021
      description: Selected in the top 8 teams for the 2021 Better working world data challenge by EY.
      img: /images/achiv.jpg
    - title: Paper - Breast cancer classification using data mining
      description: Published a paper with IJRES on breast cancer classification techniques.
      img: /images/achiv.jpg
    - title: Paper - Sequential and parallel Alpha-Beta pruning algorithm
      description: Published a paper on the working of the Alpha-Beta pruning algorithm.
      img: /images/achiv.jpg
    - title: Captain - Northeastern Cricket club sports
      description: Led the Northeastern Cricket team to various regional and national tournaments in the US.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "vijayakumar.sa@northeastern.edu"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
