baseURL: "https://sanjan-vijayakumar.netlify.app/"
languageCode: "en-us"
title: "Portfolio"

googleanalytics: UA-167646412-8
disqusShortname: 
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # home
  disable_home: false
  profile_image: "/images/profile.webp"
  name: "Sanjan Vijayakumar"
  profession: "Data Scientist"
  github: "https://github.com/sanjsvk"
  linkedin: "https://www.linkedin.com/in/sanjanvijayakumar/"
  twitter: "https://twitter.com/sanjansvk"
  instagram: "https://www.instagram.com/sanj.an/"
  facebook: "https://www.facebook.com/sanjan.vijayakumar/"

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Sanjan!<br>I'm a Data Scientist pursuing my Master's degree in Data Science at Northeastern University, Boston.<br> I'm currently working as a Data Science Intern at LabCorp.<br>I'm extremely interested in turning concepts of Data Science and Machine Learning into meaningful insights, especially in the field of healthcare. <br> [Resume](https://github.com/sanjsvk/hugo-theme/blob/master/website/Sanjan_Vijayakumar_Resume.pdf)"
  skills:
    - name: Python
      percentage: 90
    - name: SQL
      percentage: 85
    - name: Machine Learning/Deep Learning
      percentage: 80
    - name: AWS
      percentage: 75
    - name: Google Cloud Platform
      percentage: 70

  # Experience
  disable_experience: false
  experience:
    - company: "LabCorp"
      role: "Data Science Intern"
      startdate: May 2021
      enddate: present
      featuredpoints:
        - point: Created an installable data-platform package reducing data pre-processing time by 40%.
        - point: Built and deployed a recommendation system to recommend tests to users.
        - point: Devised a framework for storage and retrieval of test reference ranges in AWS.
    - company: "eMotionRx"
      role: "Data Science co-op"
      startdate: May 2020
      enddate: Dec 2020
      featuredpoints:
        - point: Orchestrated the migration of on-prem sensor data onto Google Cloud Platform.
        - point: Streamlined ETL jobs using Cloud Dataproc reducing pre-processing runtime by 30%.
        - point: Designed a random forest model with 94% accuracy for pressure distribution on a sole.
    - company: "VI-Solutions"
      role: "Data Science Intern"
      startdate: June 2018
      enddate: Sept 2018
      featuredpoints:
        - point: Accelerated run-time on an Object detection application by 30% using OpenCV.
        - point: Deployed an image classification model using ImageNet with 87% accuracy.

  # Education
  disable_education: false
  education:
    - degree: "Master of Science"
      branch: "Data Science"
      university: "Northeastern University"
      startedyear: "2019"
      graduation: "2021"
    - degree: "Bachelor of Engineering"
      branch: "Electronics and Communication"
      university: "Visvesvaraya Technological University"
      startedyear: "2015"
      graduation: "2019"

  # Projects
  disable_projects: false
  projects:
    - name: "Attention based image captioning system"
      img: /images/captioning.jpg
      githublink: "https://github.com/sanjsvk/Attention-based-image-captioning"
      description: "An image caption generator that uses a local attention model on top of a VGG-16 model as an application of NLP and deep learning"
    - name: "Yelp restaurant business analysis"
      img: /images/yelp.jpg
      githublink: "https://github.com/sanjsvk/Yelp-Restaurant-Business-Analysis"
      description: "A project which aims at gaining insights and helping restaurants objectively interpret their reviews."
    - name: "Energy consumption time-series forecasting"
      img: /images/time-series.jpg
      githublink: "https://github.com/sanjsvk/Time-Series-Forecasting"
      description: "A project to predict energy consumption in buildings with time-series hourly meter readings for one year."
    - name: "CycleGANs"
      img: /images/cyclegan.png
      githublink: "https://github.com/sanjsvk/CycleGANs"
      description: "A project to understand the operation of CycleGANs with a few examples."


  # Achievements
  disable_achievements: false
  achievements:
    - title: Semi-finalist - EY Data Science challenge 2021
      description: Selected in the top 8 teams for the 2021 Better working world data challenge by EY.
      img: /images/ey.jpeg
    - title: Breast cancer classification using data mining
      description: Published a paper with IJRES on breast cancer classification techniques.
      img: /images/data-mining.jpg
    - title: Sequential and parallel Alpha-Beta pruning algorithm
      description: Published a paper on the working of the Alpha-Beta pruning algorithm.
      img: /images/alpha-beta.png
    - title: Northeastern cricket club sports
      description: Captained the Northeastern Cricket team in various regional and national tournaments in the US.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "vijayakumar.sa@northeastern.edu"

  # Footer
  socialiconfooter: true
  recentposts: false
